---
- name: Install jdupes package
  ansible.builtin.dnf:
    name: jdupes
    state: present

- name: Create jdupes service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=jdupes deduplication service
      After=local-fs.target

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/jdupes --recurse --one-file-system --dedupe /home
    dest: /etc/systemd/system/jdupes.service
    mode: "0644"

- name: Create jdupes timer file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Run jdupes deduplication monthly

      [Timer]
      OnCalendar=monthly
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/jdupes.timer
    mode: "0644"

- name: Enable and start jdupes timer
  ansible.builtin.systemd_service:
    name: jdupes.timer
    state: started
    enabled: true
    daemon_reload: true
