---

- name: Install bees
  ansible.builtin.dnf:
    name: bees
    state: present
- name: Get UUID for dm-0
  ansible.builtin.command: blkid /dev/dm-0 -s UUID -o value
  register: duperemove_uuid
  changed_when: false
- name: Create bees config file
  ansible.builtin.copy:
    content: |
             UUID={{ duperemove_uuid.stdout }}
             OPTIONS="--verbose=3"
    dest: /etc/bees/root.conf
    mode: "0644"
- name: Create bees service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/beesd@.service.d
    state: directory
    mode: "0755"
- name: Remove bees service override
  ansible.builtin.file:
    path: /etc/systemd/system/beesd@.service.d/override.conf
    state: absent
- name: Create bees weekly wrapper service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Run bees weekly for %i (wrapper)
      After=local-fs.target

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/systemctl start beesd@%i.service
      ExecStart=/usr/bin/sleep 1h
      ExecStart=/usr/bin/systemctl stop beesd@%i.service
    dest: /etc/systemd/system/bees-weekly@.service
    mode: "0644"
- name: Create bees weekly timer
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Run bees weekly for %i

      [Timer]
      OnCalendar=weekly
      Persistent=true
      Unit=bees-weekly@%i.service

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/bees-weekly@.timer
    mode: "0644"
- name: Disable continuous bees service
  ansible.builtin.systemd_service:
    name: beesd@{{ duperemove_uuid.stdout }}.service
    state: stopped
    enabled: false
    daemon_reload: true
- name: Enable bees weekly timer
  ansible.builtin.systemd_service:
    name: bees-weekly@{{ duperemove_uuid.stdout }}.timer
    state: started
    enabled: true
