#! /bin/bash

LOG_FILE="/var/log/btrfs-balance.log"

# redirect all stdout to log gile
exec &> $LOG_FILE
# timestamp the job
echo "[`date`] btrfs balance job started."
echo "----------------------------------------"

m='/'
echo ""
echo "[`date`] balancing $m"
/usr/sbin/duperemove -hdr --hashfile=/var/tmp/duperemove.hash $m
/usr/sbin/btrfs balance start -musage=20 -dusage=20 -v $m

echo "----------------------------------------"
echo "[`date`] Balance job ended."
exit 0;

