#!/usr/bin/bash

cp ~/.config/vlc/vlcrc ~/.config/vlc/vlcrc_backup
sed -i s/.*deinterlace=.*/deinterlace=0/ ~/.config/vlc/vlcrc
sed -i s/.*postproc-q=.*/postproc-q=0/ ~/.config/vlc/vlcrc
sed -i s/.*video-filter=.*/video-filter=/ ~/.config/vlc/vlcrc
sed -i s/.*avcodec-fast=.*/avcodec-fast=1/ ~/.config/vlc/vlcrc
sed -i s/.*avcodec-skiploopfilter=.*/avcodec-skiploopfilter=4/ ~/.config/vlc/vlcrc
vlc "$@"
mv ~/.config/vlc/vlcrc_backup ~/.config/vlc/vlcrc
