- name: Remove affinity for beesd
  ansible.builtin.file:
    path: "/etc/systemd/system/beesd@.service.d/affinity.conf"
    state: absent

- name: Remove affinity for dnf5
  ansible.builtin.file:
    path: "/etc/systemd/system/dnf5-makecache.service.d/affinity.conf"
    state: absent

- name: Remove affinity for dnf
  ansible.builtin.file:
    path: "/etc/systemd/system/dnf-makecache.service.d/affinity.conf"
    state: absent

- name: Remove affinity for packagekit
  ansible.builtin.file:
    path: "/etc/systemd/system/packagekit.service.d/affinity.conf"
    state: absent

- name: Remove affinity for gnome-software
  ansible.builtin.file:
    path: "{{ var_home }}/.config/systemd/user/gnome-software.service.d/affinity.conf"
    state: absent
  become_user: "{{ var_user }}"
  become: true
