---
- name: Disable vulkan tweaks
  ansible.builtin.file:
    path: /etc/profile.d/vulkan.sh
    state: absent
- name: Set timezone
  community.general.timezone:
    name: "Europe/Prague"
- name: Disable NMI watchdog
  ansible.builtin.copy:
    content: kernel.nmi_watchdog = 0
    dest: /etc/sysctl.d/disable_watchdog.conf
    mode: "0644"
- name: TCP congestion control algorithm
  ansible.builtin.copy:
    content: net.ipv4.tcp_congestion_control = bbr
    dest: /etc/sysctl.d/tcp_congestion_control.conf
    mode: "0644"
- name: Use lz4 for zram
  community.general.ini_file:
    path: /usr/lib/systemd/zram-generator.conf
    section: zram0
    option: compression-algorithm
    value: lz4
    mode: "0644"
- name: Set zram size
  community.general.ini_file:
    path: /usr/lib/systemd/zram-generator.conf
    section: zram0
    option: zram-size
    value: ram
    mode: "0644"
- name: Set swappiness
  ansible.builtin.copy:
    content: vm.swappiness = 150
    dest: /etc/sysctl.d/swappiness.conf
    mode: "0644"
- name: Do not enable BT at boot
  community.general.ini_file:
    path: /etc/bluetooth/main.conf
    section: Policy
    option: AutoEnable
    value: "false"
    no_extra_spaces: true
    mode: "0644"
- name: Setup dnf cache
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: keepcache
    value: "False"
    no_extra_spaces: true
    mode: "0644"
- name: Setup PackageKit cache
  community.general.ini_file:
    path: /etc/PackageKit/PackageKit.conf
    section: Daemon
    option: KeepCache
    value: "false"
    no_extra_spaces: true
    mode: "0644"
- name: Remove dnf5-plugin-automatic
  ansible.builtin.dnf:
    name:
      - dnf5-plugin-automatic
    state: absent
- name: Configure disk I/O scheduler
  ansible.builtin.copy:
    content: |
      ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="none"
      ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
    dest: /etc/udev/rules.d/60-iosched.rules
    mode: "0644"
- name: Configure sysctl disk dirty ratios
  ansible.builtin.copy:
    content: |
      vm.dirty_background_ratio = 5
      vm.dirty_ratio = 10
    dest: /etc/sysctl.d/99-disk-performance.conf
    mode: "0644"
