---
  #
  # Setup sane daemon
  #
  - name: Copy udev rule to set proper group
    copy: src=70-saned.rules dest=/etc/udev/rules.d/70-saned.rules mode=0644 owner=root group=root
  - name: Disable v4l
    file: path=/etc/sane.d/v4l.conf state=absent
  - lineinfile:
      path: /etc/cups/cupsd.conf
      insertafter: '^Listen localhost:631'
      line: 'Listen 192.168.0.25:631'
  - lineinfile:
      path: /etc/cups/cupsd.conf
      firstmatch: true
      insertafter: '^  Order allow,deny'
      line: '  Allow 192.168.0.*'
  - systemd:
      name: saned.socket
      enabled: yes

