---
  #
  # Setup sane daemon
  #
  - name: Copy udev rule to set proper group
    copy: src=70-saned.rules dest=/etc/udev/rules.d/70-saned.rules mode=0644 owner=root group=root
    become: true
    become_user: root
  - name: Disable v4l
    file: path=/etc/sane.d/v4l.conf state=absent
