---
- name: Install required packages
  ansible.builtin.dnf:
    name:
      # Prepare target basics
      - ansible-core
      - ansible-collection-community-general
      - ansible-collection-ansible-posix
      # Install Fontconfig
      - curl
      - cabextract
      - xorg-x11-font-utils
      - fontconfig
    state: present

- name: Check if Microsoft Fonts are already installed
  ansible.builtin.command: rpm -q msttcore-fonts-installer # noqa: command-instead-of-module
  register: asahi_msttcore_installed
  changed_when: false
  failed_when: false
  check_mode: false

- name: Download Microsoft Fonts installer
  ansible.builtin.get_url:
    url: "https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm"
    dest: "/tmp/msttcore-fonts-installer-2.6-1.noarch.rpm"
    checksum: "sha256:55d7f3a86533225634ff3ea2384b4356d9665a29cc7eeacff16602a1714afbb4"
    mode: "0644"
  when: asahi_msttcore_installed.rc != 0

- name: Install Microsoft Fonts
  ansible.builtin.command: rpm -i --nodigest --nosignature /tmp/msttcore-fonts-installer-2.6-1.noarch.rpm # noqa: command-instead-of-module no-changed-when
  when: asahi_msttcore_installed.rc != 0
- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld.service
    enabled: true
    state: started
- name: Configure firewall services
  ansible.posix.firewalld:
    service: "{{ item.service }}"
    permanent: true
    immediate: true
    state: "{{ item.state }}"
  loop:
    - { service: ssh, state: disabled }
    - { service: mdns, state: enabled }
- name: Disable wide port ranges
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
  loop:
    - 1025-65535/udp
    - 1025-65535/tcp
- name: Check if swap config exist
  ansible.builtin.stat:
    path: /etc/tmpfiles.d/asahi-enable-zswap.conf
  register: asahi_swap
- name: Update swap config
  ansible.builtin.lineinfile:
    regexp: "compressor"
    line: "w     /sys/module/zswap/parameters/compressor         -    -    -    -    zstd"
    dest: /etc/tmpfiles.d/asahi-enable-zswap.conf
  when: asahi_swap.stat.exists
