#!/usr/bin/env bash
set -xe
if [ ! -e "/run/ostree-booted" ] && [ -x "/usr/bin/dnf" ]; then
    sudo dnf update -y
fi
if [ -e "/run/ostree-booted" ] && [ -x "/usr/bin/rpm-ostree" ]; then
    sudo rpm-ostree upgrade
fi
if command -v podman; then
    for container in $(podman ps -a | grep toolbox | awk '{ print $NF }'); do
        toolbox run -c "${container}" sudo dnf update -y
    done
fi
# brew --version fails on linux
if brew --version &> /dev/null; then
    command -v brew
    brew update
    brew upgrade
fi
