#!/usr/bin/env bash
set -xe
if [ -d /var/home ]; then
    sudo rpm-ostree upgrade
else
    sudo dnf update -y
fi
sudo dbus-run-session flatpak update -y
for container in $(podman ps -a | grep toolbox | awk '{ print $NF }'); do
    toolbox run -c "${container}" sudo yum update -y
done
sudo fwupdmgr get-updates
