syntax enable

set tabstop=8
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4

set number
set cursorline
set background=dark

set showmatch
let python_highlight_all = 1

if exists('+colorcolumn')
    set colorcolumn=80
else
    au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

set encoding=utf-8
set list listchars=tab:»·,trail:·

