---
- name: Create a user systemd directory if it does not exist
  ansible.builtin.file:
    path: '~/.config/systemd/user/'
    state: directory
    mode: '0755'
- name: Create distrobox service file
  ansible.builtin.copy:
    content: |
             [Unit]
             Description=Automatically upgrade all Distrobox containers
             [Service]
             Type=oneshot
             ExecStart=/usr/bin/distrobox-upgrade --all
    dest: '~/.config/systemd/user/distrobox-upgrade.service'
    mode: "0644"
- name: Create distrobox timer file
  ansible.builtin.copy:
    content: |
             [Unit]
             Description=Run distrobox-upgrade daily
             [Timer]
             OnCalendar=daily
             Persistent=true
             [Install]
             WantedBy=timers.target
    dest: '~/.config/systemd/user/distrobox-upgrade.timer'
    mode: "0644"
- name: Enable dristrobox timer
  ansible.builtin.systemd_service:
    name: distrobox-upgrade.timer
    state: started
    enabled: true
    scope: "user"
