#!/usr/bin/bash

/usr/bin/curl -s https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | /usr/bin/grep '^0\.0\.0\.0' | /usr/bin/awk '{ print $2 }' | /usr/bin/sort | /usr/bin/uniq | /usr/bin/sed 's,.*,address=/&/,' > /etc/NetworkManager/dnsmasq.d/ads.conf
