syntax on

set tabstop=8
set expandtab
set shiftwidth=2
set softtabstop=2

set number
set background=dark

if exists('+colorcolumn')
    set colorcolumn=80
else
    au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

set list listchars=tab:»·,trail:·

