---
#
  #
  # Setup cifs mount
  #
  - name: Install autofs
    dnf: name=autofs state=present

  - name: Check mount point
    stat: path="/media/pocitac-byt"
    register: st
  - name: Create mount point
    file: path=/media/pocitac-byt state=directory
    when: st.stat.exists == False

  - name: Check credentials file
    stat: path="/etc/credentials.txt"
    register: st
  - name: Create credentials file
    file: path=/etc/credentials.txt state=touch mode=0600
    when: st.stat.exists == False

  - name: Customize username
    lineinfile: dest=/etc/credentials.txt line=username={{ var_cifsname }}
  - name: Customize password
    lineinfile: dest=/etc/credentials.txt line=password={{ var_cifspass }}

  - name: Check config of cifs
    stat: path="/etc/auto.cifs"
    register: st
  - name: Create config of cifs
    file: path=/etc/auto.cifs state=touch mode=0644
    when: st.stat.exists == False

  - name: Change config of cifs
    lineinfile: dest=/etc/auto.cifs line="DATA -fstype=cifs,rw,noperm,credentials=/etc/credentials.txt ://{{ var_serverip }}/DATA"
  - name: Add cifs to master config
    lineinfile: dest=/etc/auto.master line="/media/pocitac-byt /etc/auto.cifs --timeout=60 --ghost"
  - name: Make sure autofs is started and enabled
    service: name=autofs state=started enabled=yes
