---
#
  #
  # Setup cifs mount
  #
  - name: Install autofs
    dnf: name=autofs state=present
  - name: Check mount point
    shell: ls /media/pocitac-byt
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Create mount point
    file: path=/media/pocitac-byt state=directory
    when: result is failed
  - name: Check credentials file
    shell: ls /etc/credentials.txt
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Create credentials file
    file: path=/etc/credentials.txt state=touch mode=600
    when: result is failed
  - name: Customize username
    lineinfile: dest=/etc/credentials.txt line=username={{ var_cifsname }}
  - name: Customize password
    lineinfile: dest=/etc/credentials.txt line=password={{ var_cifspass }}
  - name: Check config of cifs
    shell: ls /etc/auto.cifs
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Create config of cifs
    file: path=/etc/auto.cifs state=touch mode=644
    when: result is failed
  - name: Change config of cifs
    lineinfile: dest=/etc/auto.cifs line="DATA -fstype=cifs,rw,noperm,credentials=/etc/credentials.txt ://{{ var_serverip }}/DATA"
  - name: Add cifs to master config
    lineinfile: dest=/etc/auto.master line="/media/pocitac-byt /etc/auto.cifs --timeout=60 --ghost"
  - name: Make sure autofs is started and enabled
    service: name=autofs state=started enabled=yes
