---
# file: laptop.yml
- name: Configure laptop
  hosts: laptop
  remote_user: root
  roles:
    - common
    - { role: linux, become: true }
    - { role: duperemove, become: true }
    - git
    - { role: flatpaks, become: true }
