---
# file: laptop.yml
- name: Configure laptop
  hosts: laptop
  remote_user: root
  roles:
    - common
    - { role: linux, become: true }
    - { role: duperemove, become: true }
    - git
    - { role: display, become: true }
    - { role: dnf_automatic, become: true }
    - { role: flatpak, become: true }
    - containers
    - { role: google_chrome, become: true }
    - { role: rpmfusion, become: true, when: "ansible_facts['product_name'] | default('') in ['StarLite', 'Mac13,2'] or ansible_facts['nodename'] | default('') == 'studio'" }
