---
- name: Remove selected Fedora rpms
  ansible.builtin.dnf:
    name:
      - baobab
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - snapshot
      - gnome-clocks
      - gnome-connections
      - gnome-contacts
      - gnome-extensions-app
      - gnome-font-viewer
      - gnome-text-editor
      - loupe
      - gnome-logs
      - gnome-maps
      - mediawriter
      - sushi
      - evince
      - papers
      - gnome-weather
      - cheese
      - simple-scan
      - dconf-editor
    state: absent
    autoremove: true
- name: Install Fedora flatpaks
  community.general.flatpak:
    name:
      - org.gnome.baobab
      - org.gnome.Calculator
      - org.gnome.Calendar
      - org.gnome.Characters
      - org.gnome.Snapshot
      - org.gnome.clocks
      - org.gnome.Connections
      - org.gnome.Contacts
      - org.gnome.Extensions
      - org.gnome.font-viewer
      - org.gnome.TextEditor
      - org.gnome.Loupe
      - org.gnome.Logs
      - org.gnome.Maps
      - org.fedoraproject.MediaWriter
      - org.gnome.NautilusPreviewer
      - org.gnome.Papers
      - org.gnome.Weather
      - org.gnome.Cheese
      - org.gnome.SimpleScan
      - ca.desrt.dconf-editor
      - com.github.tchx84.Flatseal
    state: present
    remote: fedora
- name: Remove libreoffice rpms
  ansible.builtin.dnf:
    name:
      - libreoffice-core
      - libreoffice-base
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-impress
      - libreoffice-writer
    state: absent
    autoremove: true
    allowerasing: true
- name: Install libreoffice flatpak
  community.general.flatpak:
    name:
      - org.libreoffice.LibreOffice
    state: present
    remote: fedora
- name: Remove other rpms
  ansible.builtin.dnf:
    name:
      - gnome-boxes
      - gnome-firmware
    state: absent
    autoremove: true
- name: Install Flathub flatpak
  community.general.flatpak:
    name:
      - org.gnome.Boxes
      - com.mattjakeman.ExtensionManager
      - org.gnome.Firmware
    state: present
    remote: flathub
# https://pagure.io/workstation-ostree-config/blob/main/f/silverblue-common.yaml
- name: Install Silverblue common pkgs
  ansible.builtin.dnf:
    name:
      - desktop-backgrounds-gnome
      - gnome-shell-extension-background-logo
      - pinentry-gnome3
      # Included for now to have layered Qt5 applications use a constistent style
      # Manually included here as it is excluded from the workstation-product group
      - qadwaitadecorations-qt5
      # Include evince-thumbnailer otherwise PDF thumbnails won't work in Nautilus
      # https://github.com/fedora-silverblue/issue-tracker/issues/98
      - evince-thumbnailer
      # Include evince-previewer otherwise print previews are broken in Evince
      # https://github.com/fedora-silverblue/issue-tracker/issues/122
      - evince-previewer
      # Include totem-video-thumbnailer for video thumbnailing in Nautilus
      # https://pagure.io/fedora-workstation/issue/168
      - totem-video-thumbnailer
      # Make sure zstd and zlib-ng are installed
      - zlib-ng
      - zlib-ng-compat
      - zstd
    state: present
