---
- name: Remove selected rpms
  ansible.builtin.dnf:
    name:
      - baobab
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - snapshot
      - gnome-clocks
      - gnome-connections
      - gnome-contacts
      - gnome-extensions-app
      - gnome-font-viewer
      - gnome-text-editor
      - loupe
      - gnome-logs
      - gnome-maps
      - mediawriter
      - sushi
      - evince  # eventually Papers
      - gnome-weather
    state: absent
- name: Install flatpaks
  community.general.flatpak:
    name:
      - org.gnome.baobab
      - org.gnome.Calculator
      - org.gnome.Calendar
      - org.gnome.Characters
      - org.gnome.Snapshot
      - org.gnome.clocks
      - org.gnome.Connections
      - org.gnome.Contacts
      - org.gnome.Extensions
      - org.gnome.font-viewer
      - org.gnome.TextEditor
      - org.gnome.Loupe
      - org.gnome.Logs
      - org.gnome.Maps
      - org.fedoraproject.MediaWriter
      - org.gnome.NautilusPreviewer
      - org.gnome.Papers
      - org.gnome.Weather
    state: present
    remote: fedora
